services:
  ml-dev:
    container_name: lane-detection-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:  
        - UID=${UID}
        - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      - .:/app
    shm_size: '2gb'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]