name: lane-detection
channels:
  - pytorch
  - nvidia  
  - conda-forge
dependencies:
  # Core environment
  - python=3.11
  - pip
  
  # PyTorch with CUDA support - let conda resolve numpy version automatically
  - pytorch::pytorch=2.5.1
  - pytorch::torchvision=0.20.1
  - pytorch::torchaudio=2.5.1
  - pytorch::pytorch-cuda=12.1
  
  # Other core packages - let conda resolve versions
  - pandas
  - pillow
  - tqdm
  - pyyaml
  - jupyterlab
  
  # Install opencv via pip instead to avoid conflicts
  - pip:
    - opencv-python-headless
    - numpy
    - albumentations